name: Shopping service

on:
  push:
    branches: [ main ]
    paths : [giftingapp-shopping-service-7dac936da945]
  pull_request:
    branches: [ main ]
    paths : [giftingapp-shopping-service-7dac936da945]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: test
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Compiles
      run: | 
        cd giftingapp-shopping-service-7dac936da945
        mvn compile
    
    - name: Run test
      run: |
        cd giftingapp-shopping-service-7dac936da945
        mvn test
    
    - name: Deploy projects in local repo
      run: |
        cd giftingapp-shopping-service-7dac936da945
        mvn install
    
    - name: Login to docker
      run: docker login -u $USER_NAME -p $PASSWORD
    
    - name: Build the docker
      run: docker build ./giftingapp-shopping-service-7dac936da945 -t sathishkumar281995/giftingapp-shopping-service:latest
    
    - name: Push the docker image
      run: docker push sathishkumar281995/giftingapp-shopping-service:latest
